const { tooljetPage } = require("../../Pages/TooljetPage")
describe('ToolJet', () => {
    it('Login', () => {
        cy.Signin()
    })
    it('Test1', () => {
        cy.intercept('**/api/metadata', { fixture: 'metedata.json' })
        cy.intercept('**/api/authorize', { fixture: 'appAutorization.json' })
        cy.intercept('**/api/license/access', { fixture: 'appAccess.json' })
        cy.intercept('**/api/apps/limits', { fixture: 'appLimits.json' })
        cy.intercept('**/api/apps/workflowlimit/instance', { fixture: 'appinstances.json' })
        cy.intercept('**/api/apps/workflowlimit/workspace', { fixture: 'appworkspaces.json' })
        cy.intercept('**/api/organizations/limits', { fixture: 'apiorganizationlimits.json' })
        cy.intercept('**/api/organizations?status=active', { fixture: 'activestatus.json' })
        cy.intercept('**/api/library_apps', { fixture: 'library_apps.json' })
        cy.intercept('**/api/v2/apps/203bd50e-cef6-442a-89ba-da79cec42b8e', { fixture: 'api_v2_apps.json' })
        cy.intercept('**/api/apps?page=1&folder=&searchKey=&type=front-end', { fixture: 'searchKey.json' })
        cy.intercept('**/api/folders?searchKey=&type=front-end', { fixture: 'folderKeysearch.json' })
        cy.intercept('**/api/apps/limits', { fixture: 'limitsApp.json' })
        tooljetPage.clickCreateTempleteDropdown()
        tooljetPage.clickChoosefromTempleteDropdownList()
        tooljetPage.searchSampleTemplete('employ')
        tooljetPage.clickSearchSampleTempleteDropdownList()
        tooljetPage.clickCreateTempleteBtn()
        cy.intercept('**/api/library_apps', { fixture: 'selectedapp.json' })
        cy.intercept('**/api/apps/validate-private-app-access/d3863a4a-9952-4293-8f75-8bdf2daffe0a?access_type=edit', { fixture: 'editapp.json' })
        cy.intercept('**/api/v2/apps/d3863a4a-9952-4293-8f75-8bdf2daffe0a', { fixture: 'v2app-tool.json' })
        cy.intercept('**/api/organization-constants/environment/91c89cc3-c976-4b15-9973-0b60c2d7d39e', { fixture: 'storedcontent.json' })
        cy.intercept('**/api/license/access', { fixture: 'appAccess.json' })
        cy.intercept('**/api/data_queries?app_version_id=1408181a-49cb-478f-b7a0-4d72e0cc274d', { fixture: 'storeddataquery.json' })
        cy.intercept('**/api/app-environments/init?editing_version_id=1408181a-49cb-478f-b7a0-4d72e0cc274d', { fixture: 'initeditingAppStorage.json' })
        cy.intercept('**/api/v2/data_sources?organization_id=01980ef8-19c1-4c05-89a9-aef8be56b9d4&environment_id=91c89cc3-c976-4b15-9973-0b60c2d7d39e&app_version_id=1408181a-49cb-478f-b7a0-4d72e0cc274d', { fixture: 'storedappdata.json' })
        cy.intercept('**/api/data_queries/e0f95de5-ce2c-43d5-a081-8dcad7888068/run/91c89cc3-c976-4b15-9973-0b60c2d7d39', { fixture: 'dataquerysuccess.json' })
        tooljetPage.clickCreateAppTempleteBtn()
        // tooljetPage.clickBtnSkip()
        tooljetPage.clickTooljetLogo()
        tooljetPage.clickBackToAppsLabel()
    })
    it('Test2',()=>{
        cy.intercept('**/api/metadata', { fixture: 'metedata.json' })
        cy.intercept('**/api/authorize', { fixture: 'appAutorization.json' })
        cy.intercept('**/api/license/access', { fixture: 'appAccess.json' })
        cy.intercept('**/api/apps/limits', { fixture: 'appLimits.json' })
        cy.intercept('**/api/apps/workflowlimit/instance', { fixture: 'appinstances.json' })
        cy.intercept('**/api/apps/workflowlimit/workspace', { fixture: 'appworkspaces.json' })
        cy.intercept('**/api/organizations/limits', { fixture: 'apiorganizationlimits.json' })
        cy.intercept('**/api/organizations?status=active', { fixture: 'activestatus.json' })
        cy.intercept('**/api/library_apps', { fixture: 'library_apps.json' })
        tooljetPage.clickCreateAppBtn()
        tooljetPage.enterAppNmae('Temporary')
        tooljetPage.clickCreateAppTempleteBtn()
        cy.intercept('**/api/app-environments/init?editing_version_id=1408181a-49cb-478f-b7a0-4d72e0cc274d', { fixture: 'initeditingAppStorage.json' })
        cy.intercept('**/api/v2/data_sources?organization_id=01980ef8-19c1-4c05-89a9-aef8be56b9d4&environment_id=91c89cc3-c976-4b15-9973-0b60c2d7d39e&app_version_id=1408181a-49cb-478f-b7a0-4d72e0cc274d', { fixture: 'storedappdata.json' })
        cy.intercept('**/api/data_queries/e0f95de5-ce2c-43d5-a081-8dcad7888068/run/91c89cc3-c976-4b15-9973-0b60c2d7d39', { fixture: 'dataquerysuccess.json' })
        tooljetPage.clickTooljetLogo()
        tooljetPage.clickBackToAppsLabel()
    })
    it('Test3',()=>{
        cy.intercept('**/api/metadata', { fixture: 'metedata.json' })
        cy.intercept('**/api/authorize', { fixture: 'appAutorization.json' })
        cy.intercept('**/api/license/access', { fixture: 'appAccess.json' })
        cy.intercept('**/api/apps/limits', { fixture: 'appLimits.json' })
        cy.intercept('**/api/apps/workflowlimit/instance', { fixture: 'appinstances.json' })
        cy.intercept('**/api/apps/workflowlimit/workspace', { fixture: 'appworkspaces.json' })
        cy.intercept('**/api/organizations/limits', { fixture: 'apiorganizationlimits.json' })
        cy.intercept('**/api/organizations?status=active', { fixture: 'activestatus.json' })
        cy.intercept('**/api/library_apps', { fixture: 'library_apps.json' })
        tooljetPage.clickCardOneLabel()
        tooljetPage.clickDropdownIcon()
        cy.intercept('**/api/apps/1d61d572-6c74-45ce-af63-23f8e1ddad48/versions',{fixture:'versions.json'})
        cy.intercept('**/api/apps/1d61d572-6c74-45ce-af63-23f8e1ddad48/tables',{fixture:'tables.json'})
        cy.intercept('**/api/apps/d3863a4a-9952-4293-8f75-8bdf2daffe0a/versions/1408181a-49cb-478f-b7a0-4d72e0cc274d',{fixture:'versionstables.json'})
        tooljetPage.clickExportOption()
        cy.intercept('**/api/v2/resources/export',{fixture:'export.json'})
        tooljetPage.clickExportedSelectedVersionBtn()
        cy.readFile('cypress/downloads/test-export-1739011525597.json').should('exist');
        tooljetPage.clickCreateTempleteDropdown()
        tooljetPage.clickImportFromDevicesDropDownList()
        cy.intercept('**/api/metadata',{fixture:'importedmetadata.json'})
        cy.intercept('**/api/v2/resources/import',{fixture:'resourcesImportdata.json'})
    })
})